name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout code
        run: echo "Code checked out"
      
      - name: Install dependencies
        run: npm install
      
      - name: Build app
        run: npm run build

      - name: Get ssh key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # NEW STEP: Ensure the destination directory exists
      - name: Create destination directory on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p ~/node-app"
      
      - name: Deploy using SCP
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            -r ./src ./dist ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/node-app/
          
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            ./package.json ./package-lock.json ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/node-app/

      - name: Install dependencies and Restart app
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
            cd ~/node-app && \
            pm2 restart myapp || pm2 start npm --name 'myapp' -- run start"